name: Playwright Tests
description: This action will run the playwright test on every day at 18:00 IST, on every push, pr and save the artifacts for more info.
on:
  schedule:
    - cron: '* 18 * * *'
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
jobs:
  tests_e2e:
    name: Run end-to-end tests
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: |
          cd tests
          npm ci
          npx playwright install-deps
          npx playwright install
      - name: Run Playwright Tests
        continue-on-error: false
        working-directory: tests
        run: |
          npx playwright test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: tests/playwright-report/
          retention-days: 15
